server:
  port: 8087

spring:
  cloud:
    gateway:
      routes:
        - id: CITIZEN-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/citizen/**

        - id: VACCINATION-CENTER
          uri: http://localhost:8082
          predicates:
            - Path=/center/**

  application:
    name: SPRING-GATEWAY

